name: "Build Ray Tracing in Rust"

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */24 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
          components: rustfmt, clippy
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Run rustfmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run clippy check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all
